#!/usr/bin/env bash
set -ex

BINARY_DIR=~/.bin
BINARY_PATH="$BINARY_DIR/alacritty-v$ALACRITTY_VERSION"
source  ~/.localzshrc
eval "$($DOTFILEDIR/bin/dotfile-env)"

PLATFORM=$(echo "$(uname)" | awk '{print tolower($0)}')
MACHINE=$(uname -m)

if [ "$PLATFORM" != "linux" ]; then
  echo "Only linux is currently supported"
  exit 0
fi

if ! which alacritty-v$ALACRITTY_VERSION > /dev/null 2>&1
then
  rm -f "$BINARY_DIR/alacritty*"

  cd /tmp/
  rm -rf /tmp/alacritty

  git clone https://github.com/jwilm/alacritty.git

  cd /tmp/alacritty
  git checkout "v$ALACRITTY_VERSION"

  export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
  cargo build --release
  mv target/release/alacritty $BINARY_PATH
  ln -s $BINARY_PATH $BINARY_DIR/alacritty
  rm -rf /tmp/alacritty
fi

if [ ! -f $HOME/.local/share/applications/alacritty.desktop ]
then
  ln -s $DOTFILEDIR/alacritty/alacritty.desktop  $HOME/.local/share/applications/alacritty.desktop
fi

