#!/usr/bin/env bash
set -ex

source  ~/.localzshrc
source $DOTFILEDIR/rust/path.zsh
eval "$($DOTFILEDIR/bin/dotfile-env)"

BINARY_DIR=~/.bin
BINARY_PATH="$BINARY_DIR/alacritty-v$ALACRITTY_VERSION"
PLATFORM=$(echo "$(uname)" | awk '{print tolower($0)}')
MACHINE=$(uname -m)

if [ "$PLATFORM" != "linux" ]  && [ "$PLATFORM" != "darwin" ]; then
  echo "Only linux and MacOS is currently supported"
  exit 0
fi

if ! which alacritty-v$ALACRITTY_VERSION > /dev/null 2>&1
then
  rm -f "$BINARY_DIR/alacritty*"

  cd /tmp/
  rm -rf /tmp/alacritty

  git clone https://github.com/jwilm/alacritty.git

  cd /tmp/alacritty
  git checkout "v$ALACRITTY_VERSION"


  if [ "$PLATFORM" == "linux" ]; then
    . /etc/os-release

    PKG_CONFIG_PATH=/usr/lib64/pkgconfig

    if [ "$NAME" != "Fedora" ]
    then
      PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    fi

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH

    cargo build --release
    rm -rf $BINARY_DIR/alacritty*
    mv target/release/alacritty $BINARY_PATH
    ln -s $BINARY_PATH $BINARY_DIR/alacritty
  fi

  if [ "$PLATFORM" == "darwin" ]; then
    make app
    rm -rf /Applications/Alacritty.app 2> /dev/null
    rm -rf $BINARY_DIR/alacritty*
    cp -fr target/release/osx/Alacritty.app /Applications/
    ln -s /Applications/Alacritty.app/Contents/MacOS/alacritty $BINARY_PATH
    ln -s $BINARY_PATH $BINARY_DIR/alacritty
  fi
fi

if [ "$PLATFORM" == "linux" ] && [ ! -f $HOME/.local/share/applications/alacritty.desktop ]
then
  ln -s $DOTFILEDIR/alacritty/alacritty.desktop  $HOME/.local/share/applications/alacritty.desktop
fi

