#!/usr/bin/env bash
set -ex

BINARY_DIR=~/.bin
BINARY_PATH="$BINARY_DIR/gvm"
source  ~/.localzshrc
eval "$($DOTFILEDIR/bin/dotfile-env)"


PLATFORM=$(echo "$(expr substr $(uname -s) 1 5)" | awk '{print tolower($0)}')
DOWNLOAD_URL="https://github.com/andrewkroh/gvm/releases/download/v$GVM/gvm-$PLATFORM-amd64"

if which gvm > /dev/null 2>&1
then
  rm -f $BINARY_PATH
fi

mkdir -p $BINARY_DIR
curl -sL -o $BINARY_PATH $DOWNLOAD_URL
chmod +x $BINARY_PATH
