#!/usr/bin/env bash
set -ex

source ~/.localzshrc
source $DOTFILEDIR/system/path.zsh
source $DOTFILEDIR/brew/path.zsh
eval "$($DOTFILEDIR/bin/dotfile-env)"
source $DOTFILEDIR/golang/path.zsh
source $DOTFILEDIR/golang/env.zsh

mkdir -p $PROJECT
mkdir -p ~/.config

if [ ! -d "$PROJECT/vimrc" ]
then
  git clone https://github.com/miguel250/vimrc.git $PROJECT/vimrc
  ln -s $PROJECT/vimrc ~/.config/nvim
else
  git -C $PROJECT/vimrc pull
fi

$PROJECT/vimrc/scripts/install_deps
