#!/usr/bin/env bash
set -ex

source ~/.zshinit
source $DOTFILEDIR/system/path.zsh
source $DOTFILEDIR/brew/path.zsh
source $DOTFILEDIR/golang/path.zsh
source $DOTFILEDIR/golang/env.zsh

mkdir -p $WORKSPACE
mkdir -p ~/.config

if [ ! -d "$WORKSPACE/vimrc" ]
then
  git clone https://github.com/miguel250/vimrc.git $WORKSPACE/vimrc
fi

if [ ! -d "$HOME/.config/nvim" ]
then
  ln -s $WORKSPACE/vimrc $HOME/.config/nvim
fi

if [ ! -f "$WORKSPACE/vimrc/.git/hooks/post-merge" ]
then
  ln -s $DOTFILEDIR/nvim/post-merge $WORKSPACE/vimrc/.git/hooks
fi

$WORKSPACE/vimrc/scripts/install_deps

