#!/bin/bash
set -e

source ~/.localzshrc
eval "$($DOTFILEDIR/bin/dotfile-env)"

export ZPLUG_HOME=$HOME/.zplug

if [ ! -d "$ZPLUG_HOME" ]
then
  git clone https://github.com/zplug/zplug $ZPLUG_HOME
else
  git -C $ZPLUG_HOME fetch --all
fi

git -C $ZPLUG_HOME checkout $ZPLUG_COMMI
