#!/usr/bin/env bash
set -ex

source  ~/.localzshrc
eval "$($DOTFILEDIR/bin/dotfile-env)"

curl https://sh.rustup.rs -sSf | sh -s --  -y --no-modify-path

mkdir -p ~/.zfunc
$HOME/.cargo/bin/rustup self update
$HOME/.cargo/bin/rustup completions zsh > ~/.zfunc/_rustup

$HOME/.cargo/bin/rustup default $RUST_VERSION
