#!/usr/bin/env bash
set -ex

source  ~/.localzshrc
eval "$($DOTFILEDIR/bin/dotfile-env)"

curl https://sh.rustup.rs -sSf | sh -s --  -y --no-modify-path

~/.cargo/bin/rustup update
~/.cargo/bin/rustup completions zsh > ~/.zfunc/_rustup

rustup override set $RUST_VERSION
