#!/usr/bin/env python

import os
import platform
from subprocess import call
from os.path import expanduser
import json

OS = platform.system()
HOME = expanduser('~')
CURRENTPATH = os.path.dirname(os.path.realpath(__file__))
DOTFILEDIR = os.path.realpath('%s/../' % CURRENTPATH)


if __name__ == '__main__':
    print 'Installing gvm packages'
    packagePath = os.path.join(DOTFILEDIR, 'config.json')
    f = open(packagePath, 'r')
    config = json.loads(f.read())

    if os.path.exists('%s/.gvm' % HOME) is False:
        os.system('%s/gvm/bash.sh' % DOTFILEDIR)

    source = 'source %s/.gvm/scripts/gvm' % HOME

    os.system('/bin/bash -c "%s && gvm install  go%s --binary"' % (source, config['go_version']))
    os.system('/bin/bash -c "%s && gvm use  go%s --default "' % (source, config['go_version']))
