#!/usr/bin/env python

from __future__ import print_function

import os
import sys
import argparse
import glob
from os.path import expanduser
import platform
import shutil
from subprocess import call

HOME = expanduser('~')
OS = platform.system()
CURRENTPATH = os.path.dirname(os.path.realpath(__file__))
DOTFILEDIR = os.path.realpath('%s/../' % CURRENTPATH)
BREWPATH = "%s/brew/path.zsh"

def installGitConfiguration(name, email, backup, overwrite):
    print("Add git configuration...")

    # we want to use the git version installed by brew if available
    returnCode = call(['bash', '-c', 'source %s && git' % BREWPATH, '--version']) # check git version

    if OS == "Darwin" and returnCode == 69:
        call(['open', '-a', 'xcode'])
        exit(69)
        return

    filePath = os.path.join(HOME, '.gitconfig')
    fileExists = os.path.exists(filePath)
    if ( overwrite is False and backup is False) and fileExists:
        step = raw_input('git configuration already exists, what do you want to do? [e]xit, [b]ackup all or [o]verride all? ')

        if step.lower() == 'b':
            backup = True
        elif step.lower() == 'e':
            exit(1)
        elif step.lower() == "o":
            overwrite = True

    backupFilePath = '%s.bk' % filePath
    backupFilePathExists = os.path.exists(filePath)
    if backupFilePathExists == False and fileExists and backup:
        print("Creating backup copy of %s" % filePath)
        os.rename(filePath, '%s.bk' % filePath)
    elif fileExists:
        if os.path.isdir(filePath):
            os.rmdir(filePath)
        else:
            print("Deleting %s" % filePath)
            os.remove(filePath)


    print("Creating %s" % filePath)
    file = open(filePath, 'w')
    file.write('[include]')
    configPath =  os.path.join(DOTFILEDIR, 'git', 'config')
    file.write('\n\t path = %s' % configPath)
    file.close()

    print(name)
    while name == None:
        name = raw_input('Please enter your name: ')

    call(['bash', '-c', 'source %s && git' % BREWPATH, 'config', '--global', 'user.name', name])

    while email == None:
        email = raw_input('Please enter your email: ')

    call(['bash', '-c', 'source %s && git' % BREWPATH, 'config', '--global', 'user.email', email])

def installSymlinks(backup, overwrite=False):
    """
        Install all *.symlink inside of dotfile
    """
    print("Create symlinks...")
    os.chdir(DOTFILEDIR)

    for file in glob.glob('*/*.symlink'):
        fileName, fileExtension = os.path.splitext(os.path.basename(file))
        filePath = os.path.join(HOME, '.%s' % fileName)

        fileExists = os.path.exists(filePath)
        if ( overwrite is False and backup is False) and fileExists:
            step = raw_input('File already exists, what do you want to do? [e]xit, [b]ackup all or [o]verride all? ')

            if step.lower() == 'b':
                backup = True
            elif step.lower() == 'e':
                exit(1)
            elif step.lower() == "o":
                overwrite = True

        backupFilePath = '%s.bk' % filePath
        backupFilePathExists = os.path.exists(filePath)
        if backupFilePathExists == False and backup and fileExists:
            print("Creating backup copy of %s" % filePath)
            os.rename(filePath, '%s.bk' % filePath)
        elif fileExists:
            print("Deleting %s" % filePath)
            os.remove(filePath)

        homePath =  os.path.join(DOTFILEDIR, file)
        print("Creating a symlink to %s from %s" % (filePath, homePath))
        os.symlink(homePath, filePath)

    localFile = os.path.join(HOME, '.localzshrc')
    with open(localFile, "a+") as file:
        if "DOTFILEDIR" not in file.read():
            print("Updating .localzshrc file...")
            file.write('export DOTFILEDIR=%s\n' % DOTFILEDIR)
            file.write('export ZSH=%s/zsh' % DOTFILEDIR)


def runInstall():
    for file in glob.glob('*/install'):
        os.system(file)

    # install any extra dep needed by
    # package.
    for file in glob.glob('/extra_deps'):
        os.system(file)

def restore():
    step = raw_input('Are you sure you want to uninstall dotfiles [e]xit, [c]ontinue? ')

    if step.lower() != 'c':
        exit(1)

    print("Uninstalling")

    filePath = os.path.join(HOME, '.gitconfig')
    fileExists = os.path.exists(filePath)

    if fileExists:
        print("removing %s file" % filePath)
        os.remove(filePath)
        backupFile = "%s.bk" % filePath
        backupFileExists = os.path.exists("%s.bk" % filePath)
        if backupFileExists:
            print("restoring %s file" % backupFile)
            os.rename(backupFile, filePath)

    for file in glob.glob('*/*.symlink'):
        fileName, fileExtension = os.path.splitext(os.path.basename(file))
        filePath = os.path.join(HOME, '.%s' % fileName)
        fileExists = os.path.exists(filePath)

        if fileExists:
            print("removing %s file" % filePath)
            os.remove(filePath)
            backupFile = "%s.bk" % filePath
            backupFileExists = os.path.exists("%s.bk" % filePath)
            if backupFileExists:
                print("restoring %s file" % backupFile)
                os.rename(backupFile, filePath)

def main():
    parser = argparse.ArgumentParser(description='Install dotfiles')

    parser.add_argument('--backup', help='Backup files', action='store_false')
    parser.add_argument('--restore', help='restore to backup file', action='store_true')
    parser.add_argument('--bash', help='Enable zsh shell via bash', action='store_true')
    parser.add_argument('--name', help='Name to use for git', type=str)
    parser.add_argument('--email', help='Email to use for git', type=str)
    parser.add_argument('-s','--link', help='Don\'t run install symlink', action='store_false')
    parser.add_argument('-c','--conf', help='Don\'t run git configuration', action='store_false')
    parser.add_argument('-i','--install', help='Don\'t run */install files', action='store_false')
    parser.add_argument('-o','--overwrite', help='Overwrite all files', action='store_true')

    args = parser.parse_args()

    if args.restore:
        restore()
        return

    if args.bash:
        content = """
source %s/brew/path.zsh
export SHELL=`which zsh`
[ -z "$ZSH_VERSION" ] && exec "$SHELL" -l""" % DOTFILEDIR

        bashFile = os.path.join(HOME, '.bashrc')
        with open(bashFile, "a+") as file:
            if content not in file.read():
                print("Updating .bashrc file...")
                file.write('%s' % content)
        return

    if args.link:
        installSymlinks(args.backup, args.overwrite)

    if args.install:
        runInstall()

    if args.conf:
        installGitConfiguration(args.name, args.email, args.backup, args.overwrite)


    if args.bash != False and args.link:
        print("Run chsh -s $(which zsh) or script/bootstrap --bash to set zsh as default shell")

if __name__ == '__main__':
    main()

